In [ ]:
states = ["One","Two","Three"]

In [5]:
import numpy as np
from collections import Counter
a = [2, 1, 3, 1, 2, 3, 1, 2, 2, 2]
b = np.zeros((3,3))
for (x,y), c in Counter(zip(a, a[1:])).iteritems():
    b[x-1,y-1] = c
print b
np.array([[ 0.,  2.,  1.],
       [ 1.,  2.,  1.],
       [ 2.,  0.,  0.]])

[[0. 2. 1.]
 [1. 2. 1.]
 [2. 0. 0.]]


array([[0., 2., 1.],
       [1., 2., 1.],
       [2., 0., 0.]])

In [23]:
import numpy as np
import csv
import pylab 

In [13]:
f = open('C:\Users\DavidEttinger02\Downloads\\Book1 (1).csv','r')
fcsv = csv.reader(f)
data = [row for row in fcsv]
f.close()

In [19]:
b = np.random.randint(4, size=(5, 10))

In [ ]:
b = np.random.randint(4, size=(5, 1))

In [11]:
b = [0,1,3,2,1,2,2,1,2]
c = [0,2,3,1,1,2,2,3,3]
d = [0,2,3,1,1,1,2,3,2]

In [20]:
def get_transitions_from_star_list(a):

    b = [(a[i], a[i+1]) for i in range(len(a)-1)]

    m = np.zeros((4,4))

    for tup in b:

        i, j = tup

        i, j = int(i), int(j)

        m[i, j] = m[i,j] + 1

    return m


m = np.zeros((4,4))


for row in b:

    m = m + get_transitions_from_star_list(row)


for i in range(m.shape[0]):

    m[i] = m[i]/(sum(m[i]))

In [21]:
m

array([[0.26666667, 0.26666667, 0.2       , 0.26666667],
       [0.3       , 0.2       , 0.2       , 0.3       ],
       [0.71428571, 0.        , 0.        , 0.28571429],
       [0.15384615, 0.38461538, 0.15384615, 0.30769231]])

In [25]:
pylab.eig(m.T)

(array([ 1.        ,  0.07585881, -0.17340958, -0.12809026]),
 array([[ 0.60627069,  0.79103705, -0.72910405,  0.66723301],
        [ 0.47290279, -0.45723481,  0.64226089, -0.72218992],
        [ 0.30249471,  0.06706976,  0.20487957, -0.09848124],
        [ 0.56329012, -0.400872  , -0.11803642,  0.15343815]]))